<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLUR6w5W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLUR6w5W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLUR6w5W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLUR6w5W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLUR6w5W\App_KernelDevDebugContainer([
    'container.build_hash' => 'LUR6w5W',
    'container.build_id' => 'f2b1abca',
    'container.build_time' => 1583711957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLUR6w5W');
